# Tensor basics

In [19]:
import tensorflow as tf
import numpy as np

In [2]:
tf.Variable('test',tf.string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'test'>

In [3]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [4]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

---

In [5]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Dense(1,input_shape=(1,))
])

In [6]:
model.variables

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.1752721]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

---

#### dtype

In [15]:
vector=tf.Variable([1,2])
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [7]:
vector=tf.Variable(initial_value=[1,2])
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [8]:
vector=tf.Variable(initial_value=[1,2],dtype=tf.float32)
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [17]:
vector=tf.Variable([[1,2],[3,4],[5,6]])
vector

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [11]:
word=tf.Variable('text',dtype=tf.string)
word

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'text'>

In [13]:
complex=tf.Variable(4+3j, dtype=tf.complex64)
complex

<tf.Variable 'Variable:0' shape=() dtype=complex64, numpy=(4+3j)>

#### constant

For `tf.constant` ypu can use shape to reshape the vector into multi dimensional matrix. This operation cannot be done with `tf.Variable`.

In [14]:
tensor=tf.constant([1,2,3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [15]:
tensor=tf.constant([1,2,3,4,5,6],shape=(2,3))
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [16]:
tensor=tf.constant(1,shape=(2,3))
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

#### math operations

In [17]:
tf.add([1,2],[3,4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

In [19]:
tf.square(5)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [20]:
tf.reduce_sum([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [21]:
tf.square(5)+tf.square(2)

<tf.Tensor: shape=(), dtype=int32, numpy=29>

---

### exercise

In [21]:
x=np.arange(0,25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
x=tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [23]:
x=tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [26]:
x=tf.reshape(x,(5,5))
x

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

In [28]:
x=tf.cast(x,tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [35]:
y=tf.constant(2,dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [36]:
result=tf.math.multiply(x,y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

In [37]:
y=tf.constant([1,2,3,4,5],dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [38]:
result=x+y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

---

# Graph vs Eager execution

In [39]:
x=2
x_squared=tf.square(x)
print(f'hello {x_squared}')

hello 4


#### broadcasting

In [40]:
a=tf.constant([[1,2],[3,4]])

In [42]:
tf.add(a,1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

#### operator overloading

In [43]:
a=tf.constant([[1,2],[3,4]])

In [44]:
a**2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

#### numpy interoperability

In [45]:
import numpy as np

In [48]:
a=tf.constant(5)
b=tf.constant(3)
np.multiply(a,b)

15

---

In [49]:
ndarray=np.ones([3,3])
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
tensor=tf.multiply(ndarray,3)
tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])>

`Converting from tf to numpy`

In [51]:
tensor.numpy()

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

#### evaluating variables

In [54]:
v=tf.Variable(0.0)
v+1

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [55]:
v=tf.Variable(0.0)
v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.0>

In [57]:
v.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [56]:
v.read_value().numpy()

1.0

---

In [59]:
tensor=tf.constant([1,2,3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [61]:
tensor=tf.cast(tensor,dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

---

# Gradient tape

In [3]:
import tensorflow as tf
import numpy as np
import random

In [4]:
x_train=np.array([-1,0,1,2,3,4],dtype=float)
y_train=np.array([-3,-1,1,3,5,7],dtype=float)

In [5]:
w=tf.Variable(random.random(), trainable=True)
b=tf.Variable(random.random(), trainable=True)

In [6]:
w

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.35227615>

In [7]:
b

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.4977181>

In [19]:
def calculate_loss(y_true,y_pred):
    return tf.abs(y_true-y_pred)

In [20]:
LEARNING_RATE=0.001

In [21]:
def fit_data(w,b,x,y,lr):
    with tf.GradientTape(persistent=True) as tape:
        y_pred=w*x_train+b
        loss=calculate_loss(y,y_pred)
        
    grad_w=tape.gradient(loss,w)
    grad_b=tape.gradient(loss,b)
    
    # w-=w*grad_w*learning_rate
    # b-=b*grad_b*learning_rate
    w.assign_sub(grad_w*lr)
    b.assign_sub(grad_b*lr)

In [22]:
def calculate(w,b,x_train,y_train,lr):
    for _ in range(500):
        fit_data(w,b,x_train,y_train,lr)
    return w, b

In [23]:
w,b=calculate(w,b,x_train,y_train,LEARNING_RATE)
print(f'y ~ {w.numpy()}x+{b.numpy()}')

y ~ 1.9102635383605957x+-0.7362824082374573


In [24]:
x_train*w+b

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([-2.646546 , -0.7362824,  1.1739812,  3.0842447,  4.9945083,
        6.904772 ], dtype=float32)>

In [25]:
y_train

array([-3., -1.,  1.,  3.,  5.,  7.])

---

#### Gradient descent with gradient tape

In [26]:
def train_step(images,labels):
    with tf.GradientTape() as tape:
        logits=model(images, training=True)
        loss_value=loss_object(labels,logits)
    loss_history.append(loss_value.numpy().mean())
    grads=tape.gradient(loss_value,model.trainable_variables)
    optimizer.apply_gradients(zip(grads,model.trainable_variables))

Gradient computing

In [30]:
w=tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss=w*w*w

Derrivative of loss is now 3*w^{2}

In [31]:
tape.gradient(loss,w)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[3.]], dtype=float32)>

---

### Derrivatives

In [110]:
x=tf.Variable(4.0)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>

In [111]:
with tf.GradientTape() as tape:
    y=x*x
dy_dx=tape.gradient(y,x)

In [112]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

---

In [68]:
x=tf.ones((2,2))
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [70]:
with tf.GradientTape() as tape:
    tape.watch(x)
    y=tf.reduce_sum(x)
    z=tf.square(y)

In [71]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [72]:
z

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

Derrivative of z wrt the original input tensor x

In [73]:
dz_dx=tape.gradient(z,x)
dz_dx

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

Equations:
$$ x = \begin{bmatrix} 
   x_{1,1} & x_{1,2}\\
   x_{2,1} & x_{2,2}\\
   \end{bmatrix} $$
$$ y = x_{1,1} + x_{1,2} + x_{2,1} + x_{2,2} $$
$$ z = y^2 $$
Derrivatives
$$ \dfrac {\partial z}{\partial x} =  \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x} $$
$$ \dfrac {\partial z}{\partial y} =  2 \times y $$
$$ \dfrac {\partial y}{\partial x} = \begin{bmatrix} 
   \dfrac {\partial y}{\partial x_{1,1}} & \dfrac {\partial y}{\partial x_{1,2}}\\
   \dfrac {\partial y}{\partial x_{2,1}} & \dfrac {\partial y}{\partial x_{2,2}}\\
   \end{bmatrix} $$
Therefore:
$$ \dfrac {\partial z}{\partial x} = \begin{bmatrix} 
   \dfrac {\partial z}{\partial x_{1,1}} & \dfrac {\partial z}{\partial x_{1,2}}\\
   \dfrac {\partial z}{\partial x_{2,1}} & \dfrac {\partial z}{\partial x_{2,2}}\\
   \end{bmatrix} $$
Where:
$$ \dfrac {\partial z}{\partial x_{1,1}} = \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x_{1,1}}$$
$$ \dfrac {\partial z}{\partial x_{1,2}} = \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x_{1,2}}$$
$$ \dfrac {\partial z}{\partial x_{2,1}} = \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x_{2,1}}$$
$$ \dfrac {\partial z}{\partial x_{2,2}} = \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x_{2,2}}$$


For:
$$ x = \begin{bmatrix} 
   1 & 1\\
   1 & 1\\
   \end{bmatrix} $$
$$ y = 1 + 1 + 1 + 1 = 4$$
$$ z = y^2 = 16 $$

Partial derrivatives:
$$ \dfrac {\partial z}{\partial y} =  2 \times y = 2 \times 4 = 8 $$

$$ \dfrac {\partial y}{\partial x_{1,1}} = 1$$
$$ \dfrac {\partial y}{\partial x_{1,2}} = 1$$
$$ \dfrac {\partial y}{\partial x_{2,1}} = 1$$
$$ \dfrac {\partial y}{\partial x_{2,2}} = 1$$

Final derrivative:
$$ \dfrac {\partial z}{\partial x_{1,1}} = \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x_{1,1}} = 8 \times 1 = 8$$
$$ \dfrac {\partial z}{\partial x_{1,2}} = \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x_{1,2}} = 8 \times 1 = 8$$
$$ \dfrac {\partial z}{\partial x_{2,1}} = \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x_{2,1}} = 8 \times 1 = 8$$
$$ \dfrac {\partial z}{\partial x_{2,2}} = \dfrac {\partial z}{\partial y} \times \dfrac {\partial y}{\partial x_{2,2}} = 8 \times 1 = 8$$

$$ \dfrac {\partial z}{\partial x} = \begin{bmatrix} 
   \dfrac {\partial z}{\partial x_{1,1}} & \dfrac {\partial z}{\partial x_{1,2}}\\
   \dfrac {\partial z}{\partial x_{2,1}} & \dfrac {\partial z}{\partial x_{2,2}}\\
   \end{bmatrix} 
   =
   \begin{bmatrix} 
   8 & 8\\
   8 & 8\\
   \end{bmatrix} $$

---

#### persistent = True

Now tape can be used multiple times (not olny in `with():`)

In [77]:
x=tf.constant(3.0)

In [78]:
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    y=x*x
    z=2*y

In [79]:
dz_dx=tape.gradient(z,x)
dz_dx

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [80]:
dy_dx=tape.gradient(y,x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [81]:
del tape

---

#### high order derrivatives

In [99]:
x=tf.Variable(3.0)

The first gradient calculation of dy_dx should occur at least `inside` the outer with block.

Also note that this still won't work even if you set persistent=True for both gradient tapes.

In [100]:
with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        y=x*x*x
    dy_dx=tape1.gradient(y,x)
d2y_dx2=tape2.gradient(dy_dx,x)

In [101]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=27.0>

In [102]:
d2y_dx2

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>